/**
 * Server-safe catalog metadata: { kind → { props (Zod), slots, description } }.
 *
 * This is the data the LLM prompt builder needs to introspect. It lives
 * here (instead of in `lib/catalog/index.ts`) because that index module
 * imports the React components — every component file is `"use client"`,
 * so importing the index from a server module turns its exports into
 * Client Reference proxies and breaks `.safeParse` etc.
 *
 * `lib/llm/catalog-prompt.ts` imports `catalogComponents` from here.
 * Client code that needs the runtime registry (component registration,
 * `defineCatalog` wrapper) keeps importing from `./index`.
 *
 * Source of truth for the schemas + descriptions: `./schemas.ts`.
 */

import {
  AvatarDescription,
  AvatarSchema,
  BackButtonDescription,
  BackButtonSchema,
  BodyDescription,
  BodySchema,
  CaptionDescription,
  CaptionSchema,
  ChoiceListDescription,
  ChoiceListSchema,
  DisclosureDescription,
  DisclosureSchema,
  DividerDescription,
  DividerSchema,
  EmailGateDescription,
  EmailGateSchema,
  EmailInputDescription,
  EmailInputSchema,
  EyebrowDescription,
  EyebrowSchema,
  GroupDescription,
  GroupSchema,
  HeadingDescription,
  HeadingSchema,
  IconBadgeDescription,
  IconBadgeSchema,
  ImageChoiceGridDescription,
  ImageChoiceGridSchema,
  LongTextDescription,
  LongTextSchema,
  MultiChoiceDescription,
  MultiChoiceSchema,
  NumberInputDescription,
  NumberInputSchema,
  PoweredFooterDescription,
  PoweredFooterSchema,
  PriceCardDescription,
  PriceCardSchema,
  PrimaryCTADescription,
  PrimaryCTASchema,
  ProgressBarDescription,
  ProgressBarSchema,
  ResultBadgeDescription,
  ResultBadgeSchema,
  ResultHeroDescription,
  ResultHeroSchema,
  ScalePickerDescription,
  ScalePickerSchema,
  ScreenDescription,
  ScreenSchema,
  SecondaryCTADescription,
  SecondaryCTASchema,
  ShortTextDescription,
  ShortTextSchema,
  SocialProofDescription,
  SocialProofSchema,
  SpacerDescription,
  SpacerSchema,
  StackDescription,
  StackSchema,
  ToggleRowDescription,
  ToggleRowSchema,
} from "./schemas";

export const catalogComponents = {
  Screen: { props: ScreenSchema, slots: [] as const, description: ScreenDescription },
  Stack: { props: StackSchema, slots: [] as const, description: StackDescription },
  Group: { props: GroupSchema, slots: [] as const, description: GroupDescription },
  Spacer: { props: SpacerSchema, slots: [] as const, description: SpacerDescription },
  Divider: { props: DividerSchema, slots: [] as const, description: DividerDescription },
  Heading: { props: HeadingSchema, slots: [] as const, description: HeadingDescription },
  Body: { props: BodySchema, slots: [] as const, description: BodyDescription },
  Eyebrow: { props: EyebrowSchema, slots: [] as const, description: EyebrowDescription },
  Caption: { props: CaptionSchema, slots: [] as const, description: CaptionDescription },
  ChoiceList: { props: ChoiceListSchema, slots: [] as const, description: ChoiceListDescription },
  MultiChoice: { props: MultiChoiceSchema, slots: [] as const, description: MultiChoiceDescription },
  ImageChoiceGrid: { props: ImageChoiceGridSchema, slots: [] as const, description: ImageChoiceGridDescription },
  ScalePicker: { props: ScalePickerSchema, slots: [] as const, description: ScalePickerDescription },
  ShortText: { props: ShortTextSchema, slots: [] as const, description: ShortTextDescription },
  LongText: { props: LongTextSchema, slots: [] as const, description: LongTextDescription },
  EmailInput: { props: EmailInputSchema, slots: [] as const, description: EmailInputDescription },
  NumberInput: { props: NumberInputSchema, slots: [] as const, description: NumberInputDescription },
  ToggleRow: { props: ToggleRowSchema, slots: [] as const, description: ToggleRowDescription },
  PrimaryCTA: { props: PrimaryCTASchema, slots: [] as const, description: PrimaryCTADescription },
  SecondaryCTA: { props: SecondaryCTASchema, slots: [] as const, description: SecondaryCTADescription },
  ProgressBar: { props: ProgressBarSchema, slots: [] as const, description: ProgressBarDescription },
  BackButton: { props: BackButtonSchema, slots: [] as const, description: BackButtonDescription },
  ResultBadge: { props: ResultBadgeSchema, slots: [] as const, description: ResultBadgeDescription },
  ResultHero: { props: ResultHeroSchema, slots: [] as const, description: ResultHeroDescription },
  PriceCard: { props: PriceCardSchema, slots: [] as const, description: PriceCardDescription },
  EmailGate: { props: EmailGateSchema, slots: [] as const, description: EmailGateDescription },
  SocialProof: { props: SocialProofSchema, slots: [] as const, description: SocialProofDescription },
  Disclosure: { props: DisclosureSchema, slots: [] as const, description: DisclosureDescription },
  Avatar: { props: AvatarSchema, slots: [] as const, description: AvatarDescription },
  IconBadge: { props: IconBadgeSchema, slots: [] as const, description: IconBadgeDescription },
  PoweredFooter: { props: PoweredFooterSchema, slots: [] as const, description: PoweredFooterDescription },
};
